Refactor GSoc General Guidelines
sef-global/sef-handbook pull request #45
Opened 2024-02-04 19:19 UTC by Dilini-457

To suggest a change to the [Handbook](https://handbook.sefglobal.org/), please review the [Handbook Guidlines](https://handbook.sefglobal.org/organisation/handbook/usage#handbook-guidelines) section.

### Purpose:
The purpose of this PR is to fix #44

### Related to:

### Please provide a brief explanation for this change:

**Preview Link:**

https://pr-{PR_NUMBER}-sef-handbook.surge.sh/

### Please indicate the types of revisions being suggested for the Handbook (please check all that apply):

* [ ] Small improvement (typos, clarifications, etc.)
* [ ] Adding a new section
* [ x ] Modifying existing section
* [ ] Documenting a new process
* [ ] Adding a new page or directory
* [ ] Other

### Author Checklist

* [ x ] Provided a concise title for the PR
* [ ] Provided a brief explanation for this change (Say why not just what)
  * (Attach screenshots, Slack conversations, etc. as necessary)
* [ ] Indicated the types of changes included in this PR
* [ ] Verified that no confidential data is in this PR
* [ ] Posted an update in [#handbook](https://sefheadquarters.slack.com/archives/C0376JVK2HF) channel
* [ ] If the changes affect team members, or warrant an announcement in another way, please consider posting an update in [#general](https://sefheadquarters.slack.com/archives/CJ89Y7JAV) channel

2024-02-05 03:52 UTC, anjula-sack requested changes
Requested some minor changes @Dilini-457

2024-02-05 03:52 UTC, anjula-sack commented on docs/gsoc-contributor-guidance.md
> +4. Introduce yourself in the dedicated thread on SEF Hive to connect with the community.
```suggestion
4. Introduce yourself in the [introduction](https://sef.discourse.group/t/welcome-please-introduce-yourself/7?u=anjisvj) thread on SEF Hive to connect with the community.
```

2024-02-05 03:52 UTC, anjula-sack commented on docs/gsoc-contributor-guidance.md
> +2. Initiate your involvement by asking questions and exploring project ideas in the GSoC category on SEF Hive.
```suggestion
2. Initiate your involvement by asking questions and exploring project ideas on SEF Hive.
```

2024-02-05 03:52 UTC, anjula-sack commented on docs/gsoc-contributor-guidance.md
> +1. Get acquainted with SEF and your chosen projects by referring to the Developer Guide and Getting Started as a Developer.
```suggestion
1. Get acquainted with SEF and your chosen projects by referring to the [Getting Started](https://handbook.sefglobal.org/engineering-team/team) as a Developer.
```

2024-02-07 07:55 UTC, anjula-sack commented
@Dilini-457 can you update the PR with the changes?

2024-02-12 17:27 UTC, anjula-sack commented
@Dilini-457 can you update the PR with the changes?

2024-02-15 17:57 UTC, Dilini-457 commented
@anjula-sack Updated the PR with requested changes.

2024-02-16 04:37 UTC, anjula-sack approved these changes
Thank you! @Dilini-457

2024-02-16 04:37 UTC, merged