Add GitHub templates
sef-global/sef-handbook pull request #6
Opened 2022-09-05 16:37 UTC by DilinaBandara

**Preview Link:**

https://pr-{PR_NUMBER}-sef-handbook.surge.sh/

2022-09-05 16:41 UTC, DilinaBandara commented
@anjula-sack  Added the GitHub templates

2022-09-05 18:29 UTC, anjula-sack requested changes

2022-09-05 18:29 UTC, anjula-sack commented on .github/PULL_REQUEST_TEMPLATE.md
> +https://pr-{PR_NUMBER}-sef-site.surge.sh/
This part is not required. @DilinaBandara

2022-09-06 04:09 UTC, anjula-sack commented
Can you link the issue to the description?

2022-09-06 12:05 UTC, anjula-sack approved these changes
Thank you! @DilinaBandara

2022-09-06 12:05 UTC, merged